# version: '3.8'
 
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lunary_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
 
  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://myuser:postgres@postgres:5432/lunary_db
      JWT_SECRET: "yoursupersecret"
      APP_URL: "http://localhost:3000"
      API_URL: "http://localhost:8081"
      NEXT_PUBLIC_API_URL: "http://localhost:8081"
    ports:
      - "8081:8081"
    volumes:
      - ./packages/backend:/packages/backend
      - ./packages/backend/node_modules:/packages/backend/node_modules
      # - ./packages/db:/usr/src/app/db/
    command: ["npm", "run", "start"]
    # , "&&" , "tsx", "src/index.ts"
 
  frontend:
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./packages/frontend:/packages/frontend
      - ./packages/frontend/node_modules:/packages/frontend/node_modules
    depends_on:
      - backend
    command: ["npm", "run", "start"]
 
volumes:
  postgres_data: